### ISSUE TITLE
Rspec results when test passes

### ISSUE THREAD

**Issue by pBorak** [aaronhallaert/continuous-testing.nvim#25]
Hey, I was looking forward to testing out this plugin but for RSpec, it seems to be broken for me.

When a test fails I am getting a notification (via notify) about failures, signs are updated. 
The problem I get ironically occurs when the test passes.
I am getting the notification "2 Examples, 0 failures" - nothing like the "All tests passed", signs are not updated in the buffer (**though in Telescope they do**).

Also, I cannot find a relevant piece of code for Rspec similar to the one you do for vite when all test passes [here](https://github.com/aaronhallaert/continuous-testing.nvim/blob/603a1c4c707e32341d4ae0eb37528ca65ed62421/lua/continuous-testing/languages/javascript/vitest.lua#L125)

**Comment by aaronhallaert** [comment]
The notification message is extracted from Rspec's json formatter. The assignment of `summary_line` can be found [here](https://github.com/aaronhallaert/continuous-testing.nvim/blob/603a1c4c707e32341d4ae0eb37528ca65ed62421/lua/continuous-testing/languages/ruby/rspec/state-rspec.lua#L44). So, "2 Examples, 0 failures" is expected behavior.

I'll need some extra information to reproduce the bug of the signs that do not update. To start, what is your neovim version? What is your rspec version? Can you run the test with `format --json` and paste the result here?

**Comment by pBorak** [comment]
I am using Nightly neovim  and rspec version `3.12.0`
```
❯ nvim --version
NVIM v0.9.0-dev-2090+ge1f03c481-dirty
```

I have spent some additional time debugging. Here are my observations:

- I was wrong that the signs were working. I thought so because I've seen signs of skipped and failed tests. As it turns out, they come from diagnostics.

- I think the problem may lie in this [part](https://github.com/aaronhallaert/continuous-testing.nvim/blob/603a1c4c707e32341d4ae0eb37528ca65ed62421/lua/continuous-testing/languages/common.lua#L30).
The `start_sign` never gets cleared (Is the line number a valid sign id?).
If I remove the logic that sets start_sign I get signs placed correctly, though diagnostics signs override those from `continuous-testing `

**Comment by aaronhallaert** [comment]
There is indeed a problem with the line-number/index for signs. Solved the issue in this PR https://github.com/aaronhallaert/continuous-testing.nvim/pull/27. Thanks for investigating!

Not sure if this will solve your problem entirely. Can you please try on the PR branch? Let me know if it still doesn't work.

**Comment by pBorak** [comment]
Your changes seem to fix the issue.
Thanks for looking into it!
